In [ ]:
# # Data Preprocessing

# ## What is Data Preprocessing?

# Data Preprocessing is the process of cleaning and preparing raw data before training a Machine Learning model.

# Real-world data is rarely clean. It often contains:

# - Missing Values
# - Duplicate Data
# - Categorical Values
# - Different Scales
# - Incorrect Data Types

# If we train a model on unclean data, the model's performance will be poor.

# ## Why is Data Preprocessing Important?

# - Improves Model Accuracy
# - Makes Data Consistent
# - Reduces Errors
# - Helps Algorithms Learn Better

# ## Steps Covered

# - Missing Values
# - Encoding
# - Feature Scaling

Code Cell 1

In [1]:
# ============================================================
# Import Libraries
# ============================================================

import pandas as pd
import numpy as np

Code Cell 2
Create Sample Dataset

In [2]:
df = pd.DataFrame({

    "Age":[22,25,np.nan,30,28,np.nan],

    "Salary":[25000,30000,28000,np.nan,45000,50000],

    "Gender":["Male","Female","Female","Male","Female","Male"]

})

df

    Age   Salary  Gender
0  22.0  25000.0    Male
1  25.0  30000.0  Female
2   NaN  28000.0  Female
3  30.0      NaN    Male
4  28.0  45000.0  Female
5   NaN  50000.0    Male

Code Cell 3
Check Missing Values

In [ ]:
df.isnull()

# True → Missing Value

# False → Available Value

     Age  Salary  Gender
0  False   False   False
1  False   False   False
2   True   False   False
3  False    True   False
4  False   False   False
5   True   False   False

Code Cell 4
Count Missing Values

In [4]:
df.isnull().sum()

Age       2
Salary    1
Gender    0
dtype: int64

Code Cell 5
Fill Missing Values (Mean)

In [5]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
df

     Age   Salary  Gender
0  22.00  25000.0    Male
1  25.00  30000.0  Female
2  26.25  28000.0  Female
3  30.00  35600.0    Male
4  28.00  45000.0  Female
5  26.25  50000.0    Male

Code Cell 6
Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df["Gender"] = encoder.fit_transform(df["Gender"])
df

     Age   Salary  Gender
0  22.00  25000.0       1
1  25.00  30000.0       0
2  26.25  28000.0       0
3  30.00  35600.0       1
4  28.00  45000.0       0
5  26.25  50000.0       1

Code Cell 7
Standard Scaling

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["Age","Salary"]] = scaler.fit_transform(

    df[["Age","Salary"]]

)

df

        Age    Salary  Gender
0 -1.717259 -1.164437       1
1 -0.505076 -0.615174       0
2  0.000000 -0.834879       0
3  1.515229  0.000000       1
4  0.707107  1.032614       0
5  0.000000  1.581876       1

Code Cell 8
Min-Max Scaling

In [8]:
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({

    "Age":[22,25,28,30,35]

})

scaler = MinMaxScaler()

df["Age"] = scaler.fit_transform(df[["Age"]])

df

        Age
0  0.000000
1  0.230769
2  0.461538
3  0.615385
4  1.000000

📝 Machine Learning Flow

In [9]:
# Raw Data
# ↓
# Missing Values
# ↓
# Encoding
# ↓
# Scaling
# ↓
# Train-Test Split
# ↓
# Machine Learning Model