In [1]:
# # Feature Engineering

# ## What is Feature Engineering?

# Feature Engineering is the process of transforming raw data into a format that Machine Learning algorithms can understand and learn from.

# Good features lead to better models.

# ## Why is Feature Engineering Important?

# - Improves model performance
# - Converts categorical data into numerical form
# - Removes unnecessary information
# - Makes data suitable for Machine Learning

# ## Topics Covered

# - One-Hot Encoding
# - Ordinal Encoding
# - Feature Selection
# - fit()
# - transform()
# - fit_transform()

Code Cell 1

In [2]:
import pandas as pd

df = pd.DataFrame({

    "City":["Delhi","Mumbai","Delhi","Pune","Mumbai"],

    "Education":["UG","PG","UG","PhD","PG"],

    "Salary":[30000,50000,35000,70000,60000]

})

df

     City Education  Salary
0   Delhi        UG   30000
1  Mumbai        PG   50000
2   Delhi        UG   35000
3    Pune       PhD   70000
4  Mumbai        PG   60000

Code Cell 2
One-Hot Encoding

In [6]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(

    sparse_output=False # OneHotEncoder returns a Sparse Matrix.

)

city = encoder.fit_transform(

    df[["City"]]

)

city

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

Code Cell 3
Column Names

In [7]:
city_df = pd.DataFrame(

    city,

    columns=encoder.get_feature_names_out()

)

city_df

   City_Delhi  City_Mumbai  City_Pune
0         1.0          0.0        0.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0

Code Cell 4
Merge with Original Dataset

In [8]:
df = pd.concat(

    [

        df.drop("City", axis=1),

        city_df

    ],

    axis=1

)

df

  Education  Salary  City_Delhi  City_Mumbai  City_Pune
0        UG   30000         1.0          0.0        0.0
1        PG   50000         0.0          1.0        0.0
2        UG   35000         1.0          0.0        0.0
3       PhD   70000         0.0          0.0        1.0
4        PG   60000         0.0          1.0        0.0

Code Cell 5
Ordinal Encoding

In [9]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(

    categories=[

        [

            "UG",

            "PG",

            "PhD"

        ]

    ]

)

df["Education"] = encoder.fit_transform(

    df[["Education"]]

)

df

   Education  Salary  City_Delhi  City_Mumbai  City_Pune
0        0.0   30000         1.0          0.0        0.0
1        1.0   50000         0.0          1.0        0.0
2        0.0   35000         1.0          0.0        0.0
3        2.0   70000         0.0          0.0        1.0
4        1.0   60000         0.0          1.0        0.0

Code Cell 6
Understanding fit()

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(

    df[["Salary"]]

)

StandardScaler()

Code Cell 7
Understanding transform()

In [11]:
scaled = scaler.transform(

    df[["Salary"]]

)

scaled

array([[-1.2694909 ],
       [ 0.06681531],
       [-0.93541435],
       [ 1.40312152],
       [ 0.73496842]])

Code Cell 8
Understanding fit_transform()

In [12]:
scaler = StandardScaler()

salary = scaler.fit_transform(

    df[["Salary"]]

)

salary

array([[-1.2694909 ],
       [ 0.06681531],
       [-0.93541435],
       [ 1.40312152],
       [ 0.73496842]])